name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          PORTFOLIO_ID: ${{ secrets.PORTFOLIO_ID }}
        
      - name: Lint code
        run: npm run lint

  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build client
        run: npm run build:client
          
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Deploy to Cloudflare Workers
        run: |
          echo "Deploying worker..."
          wrangler deploy
          
          echo "Setting secrets..."
          echo "${{ secrets.API_BASE_URL }}" | wrangler secret put API_BASE_URL || echo "Failed to set API_BASE_URL, but continuing..."
          echo "${{ secrets.PORTFOLIO_ID }}" | wrangler secret put PORTFOLIO_ID || echo "Failed to set PORTFOLIO_ID, but continuing..."
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}